backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img
publish_mode: editorial_workflow

collections:
  - name: "case-studies"
    label: "Case Studies"
    label_singular: "Case Study"
    folder: "src/pages/case-studies"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "case-studies"}
      - {label: "Create Page", name: "createPage", widget: "hidden", default: true}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Partner Name", name: "partnerName", widget: "string"}
      - {label: "Texture", name: "texture", widget: image}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Featured Post", name: "featuredpost", widget: "boolean"}
      - {label: "Secondary Layout", name: "secondaryLayout", widget: "boolean"}
      - {label: "Modified Texture", name: "modifiedTexture", widget: "boolean", default: false}
      - {label: "Featured Image", name: "featuredimage", widget: image}
      - {label: "Home Image", name: "homeimage", widget: image}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "List Image Artwork", name: "listImageArtwork", widget: image}
      - {label: "List Image Frame", name: "listImageFrame", widget: image}
      - {label: "List Order", name: "listOrder", widget: "number"}
      - label: "SEO"
        name: "seo"
        widget: "object"
        fields:
         - {label: "Meta Title", name: "metaTitle", widget: "string"}
         - {label: "Meta Description", name: "metaDescription", widget: "string"}
         - {label: "Social Sharing Copy", name: "socialShareCopy", widget: "string"}

  - name: "blog-posts"
    label: "Blog"
    label_singular: "Blog Post"
    folder: "src/pages/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Create Page", name: "createPage", widget: "hidden", default: true}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Headline", name: "headline", widget: "string", required: false}
      - label: "Author"
        name: "author"
        widget: "select"
        required: true
        options:
         - { label: "Andy Shaw", value: "Andy Shaw" }
         - { label: "Anne Parmer", value: "Anne Parmer" }
         - { label: "Dominic Prestifilippo", value: "Dominic Prestifilippo" }
         - { label: "Evan Keller", value: "Evan Keller" }
         - { label: "Heather Heigel", value: "Heather Heigel" }
         - { label: "Laura Moyer", value: "Laura Moyer" }
         - { label: "Lauren McAteer", value: "Lauren McAteer" }
         - { label: "Madeline Pellman", value: "Madeline Pellman" }
         - { label: "Mike Koser", value: "Mike Koser" }
         - { label: "Ryan Eagan", value: "Ryan Eagan" }
         - { label: "Shane Shearer", value: "Shane Shearer" }
         - { label: "Winton DeShong", value: "Winton DeShong" }
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured", name: "featured", widget: "boolean", required: false}
      - label: "Featured Color"
        name: "featuredColor"
        widget: "select"
        required: false
        options:
         - { label: "Fresh", value: "-fresh" }
         - { label: "After Hours", value: "-after-hours" }
         - { label: "Violet Blue", value: "-violet-blue" }
         - { label: "Throwback Pink", value: "-throwback-pink" }
         - { label: "Siracha", value: "-siracha" }
         - { label: "Tea", value: "-tea" }
         - { label: "Eraser", value: "-eraser" }
         - { label: "Sticky Blue", value: "-sticky-blue" }
         - { label: "Center Lane", value: "-center-lane" }
        default: { label: "Fresh", value: "-fresh" }
      - label: "Featured Image"
        name: "featuredImage"
        widget: "object"
        required: false
        fields:
         - {label: "Image", name: "image", widget: "image", required: false}
         - {label: "Description", name: "description", widget: "string", required: false}
      - label: "Tile Image"
        name: "tileImage"
        widget: "object"
        fields:
         - {label: "Image", name: "image", widget: "image"}
         - {label: "Description", name: "description", widget: "string"}
      - label: "Post Image"
        name: "postImage"
        widget: "object"
        fields:
         - {label: "Image", name: "image", widget: "image"}
         - {label: "Description", name: "description", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown", buttons: ["bold", "italic", "code", "link", "heading-two", "quote", "bulleted-list", "numbered-list"]}
      - label: "Category"
        name: "category"
        widget: "select"
        options: ["Agency", "Catamaran", "Design/UX", "Engineering", "Partners", "Strategy"]
        default: "Agency"
      - label: "SEO"
        name: "seo"
        widget: "object"
        fields:
         - {label: "Meta Title", name: "metaTitle", widget: "string"}
         - {label: "Meta Description", name: "metaDescription", widget: "string"}
         - {label: "Social Sharing Copy", name: "socialShareCopy", widget: "string"}

  - name: "employees"
    label: "Employees"
    label_singular: "Employee"
    folder: "src/data/employees"
    create: true
    identifier_field: "name"
    fields:
      - {label: "Create Page", name: "createPage", widget: "hidden", default: false}
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Job Title", name: "position", widget: "string"}
      - {label: "Easter Egg", name: "easterEgg", widget: "string"}
      - label: "Author Photo"
        name: "authorPhoto"
        required: false
        widget: "object"
        fields:
         - {label: "Image", name: "image", widget: "image"}
         - {label: "Description", name: "description", widget: "string"}
      - label: "Social Links"
        label_singular: "Link"
        name: "socialLinks"
        required: false
        widget: "list"
        fields:
        - label: "Platform"
          name: "platform"
          widget: "select"
          options: ["Dribbble", "Facebook", "GitHub", "Instragram", "LinkedIn", "Twitter"]
        - {label: "URL", name: "url", widget: "string"}

  - name: "careers"
    label: "Careers"
    label_singular: "Career"
    folder: "src/pages/careers"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "careers-detail-page"}
      - {label: "Create Page", name: "createPage", widget: "hidden", default: true}
      - {label: "Title", name: "title", widget: "string"}
      - label: "Function"
        name: "function"
        widget: "select"
        options: ["Design", "Engagement", "Engineering", "Partnerships", "Strategy", "UX/HCD"]
        default: "Design"
      - {label: "Short Description", name: "description", widget: "string"}
      - {label: "Application URL", name: "applicationUrl", widget: "string"}
      - {label: "Active", name: "active", widget: "boolean", required: false}
      - {label: "Body", name: "body", widget: "markdown", buttons: ["bold", "italic", "code", "link", "bulleted-list", "numbered-list"]}
      - label: "SEO"
        name: "seo"
        widget: "object"
        fields:
         - {label: "Meta Title", name: "metaTitle", widget: "string"}
         - {label: "Meta Description", name: "metaDescription", widget: "string"}
         - {label: "Social Sharing Copy", name: "socialShareCopy", widget: "string"}

  - name: "values"
    label: "Core Values"
    label_singular: "Core Value"
    folder: "src/data/values"
    create: true
    identifier_field: "name"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "core-value"}
      - {label: "Create Page", name: "createPage", widget: "hidden", default: false}
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Priority", name: "priority", widget: "number", valueType: "int"}
      - {label: "Description", name: "description", widget: "text"}
      - label: "Image"
        name: "image"
        widget: "object"
        fields:
         - {label: "Source", name: "src", widget: "image"}
         - {label: "Description", name: "description", widget: "string"}
         - {label: "Include Space", name: "space", widget: "boolean"}

  - name: "perks"
    label: "Perks"
    label_singular: "Perk"
    folder: "src/data/perks"
    create: true
    identifier_field: "name"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "perk"}
      - {label: "Create Page", name: "createPage", widget: "hidden", default: false}
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Priority", name: "priority", widget: "number", valueType: "int"}
      - {label: "Description", name: "description", widget: "text"}

  - name: "departments"
    label: "Departments"
    label_singular: "Department"
    folder: "src/data/departments"
    create: true
    identifier_field: "name"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "department"}
      - {label: "Create Page", name: "createPage", widget: "hidden", default: false}
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Priority", name: "priority", widget: "number", valueType: "int"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Roles", name: "rolesList", widget: "list"}
      - {label: "Department Illustration", name: "deptImg", widget: image}


  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: "Create Page", name: "createPage", widget: "hidden", default: true}
          - {label: Title, name: title, widget: string}
          - {label: Secondary, name: secondaryTitle, widget: string}
          - {label: Subtitle, name: subTitle, widget: string}
          - label: "SEO"
            name: "seo"
            widget: "object"
            fields:
             - {label: "Meta Title", name: "metaTitle", widget: "string"}
             - {label: "Meta Description", name: "metaDescription", widget: "string"}
             - {label: "Social Sharing Copy", name: "socialShareCopy", widget: "string"}

      - file: "src/pages/contact.md"
        label: "Contact Page"
        name: "contact"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "contact-page"}
          - {label: "Create Page", name: "createPage", widget: "hidden", default: true}
          - {label: Title, name: title, widget: string}
          - {label: Secondary, name: secondaryTitle, widget: string}
          - {label: Subtitle, name: subTitle, widget: string}
          - {label: Street Address Line One, name: streetAddressLineOne, widget: string}
          - {label: Street Address Line Two, name: streetAddressLineTwo, widget: string}
          - {label: Map Link, name: mapLink, widget: string}
          - {label: Phone Number, name: phoneNumber, widget: string}
          - {label: Directions, name: directions, widget: string}
          - label: "SEO"
            name: "seo"
            widget: "object"
            fields:
             - {label: "Meta Title", name: "metaTitle", widget: "string"}
             - {label: "Meta Description", name: "metaDescription", widget: "string"}
             - {label: "Social Sharing Copy", name: "socialShareCopy", widget: "string"}
      - file: "src/pages/about.md"
        label: "About Page"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Create Page", name: "createPage", widget: "hidden", default: true}
          - {label: Title, name: title, widget: string}
          - {label: Secondary, name: secondaryTitle, widget: string}
          - {label: Subtitle, name: subTitle, widget: string}
          - label: "SEO"
            name: "seo"
            widget: "object"
            fields:
             - {label: "Meta Title", name: "metaTitle", widget: "string"}
             - {label: "Meta Description", name: "metaDescription", widget: "string"}
             - {label: "Social Sharing Copy", name: "socialShareCopy", widget: "string"}
      - file: "src/pages/blog.md"
        label: "Blog Page"
        name: "blog"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-page"}
          - {label: "Create Page", name: "createPage", widget: "hidden", default: true}
          - {label: Title, name: title, widget: string}
          - {label: Secondary, name: secondaryTitle, widget: string}
          - {label: Subtitle, name: subTitle, widget: string}
          - label: "SEO"
            name: "seo"
            widget: "object"
            fields:
             - {label: "Meta Title", name: "metaTitle", widget: "string"}
             - {label: "Meta Description", name: "metaDescription", widget: "string"}
             - {label: "Social Sharing Copy", name: "socialShareCopy", widget: "string"}
      - file: "src/pages/privacy-policy.md"
        label: "Privacy Page"
        name: "privacy"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "privacy-page"}
          - {label: "Create Page", name: "createPage", widget: "hidden", default: true}
          - {label: Title, name: title, widget: string}
          - {label: Secondary, name: secondaryTitle, widget: string}
          - {label: Subtitle, name: subTitle, widget: string}
          - {label: "Body", name: "body", widget: "markdown", buttons: ["bold", "italic", "code", "link", "heading-three", "quote", "bulleted-list", "numbered-list"]}
          - label: "SEO"
            name: "seo"
            widget: "object"
            fields:
             - {label: "Meta Title", name: "metaTitle", widget: "string"}
             - {label: "Meta Description", name: "metaDescription", widget: "string"}
             - {label: "Social Sharing Copy", name: "socialShareCopy", widget: "string"}
      - file: "src/pages/careers.md"
        label: "Careers"
        name: "careers"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "careers-page"}
          - {label: "Create Page", name: "createPage", widget: "hidden", default: true}
          - {label: Title, name: title, widget: string}
          - {label: Secondary, name: secondaryTitle, widget: string}
          - {label: Subtitle, name: subTitle, widget: string}
          - {label: "Values Heading", name: "valuesTitle", widget: "string"}
          - {label: "Values Text", name: "valuesText", widget: "text"}
          - {label: "Position Empty Text", name: "positionEmptyText", widget: "text"}
          - label: "SEO"
            name: "seo"
            widget: "object"
            fields:
             - {label: "Meta Title", name: "metaTitle", widget: "string"}
             - {label: "Meta Description", name: "metaDescription", widget: "string"}
             - {label: "Social Sharing Copy", name: "socialShareCopy", widget: "string"}
  - name: "clients"
    label: "Clients"
    label_singular: "Client"
    folder: "src/data/clients"
    create: true
    identifier_field: "name"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "client"}
      - {label: "Create Page", name: "createPage", widget: "hidden", default: false}
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Priority", name: "priority", widget: "number", valueType: "int"}
      - label: "Logo"
        name: "logo"
        required: true
        widget: "object"
        fields:
         - {label: "Image", name: "image", widget: "image"}
         - {label: "Description", name: "description", widget: "string"}

